# "/" + 仓库的名字. 资源文件的路径组成部分
baseurl: "/my-favorite-documentaries"

# 网站的主标题
title: "2022 collections"
# 网站副标题
subTitle: "记录2022年看过的我喜爱的记录片"

# 其它配置, 可忽略, 无需修改
permalink: /:title/

---
title:  "道码旦・由来"
subtitle: "关注我们公众号/微博：codingirlsclub"
author: "吾塘"
avatar: "assets/images/authors/logo.jpg"
image: "assets/images/1.jpg"
---
